import { Product } from './types';

export const initialProducts: Product[] = [
  {
    id: "1",
    title: "فيلا فاخرة للإيجار بقرطاج",
    description: "فيلا مميزة مع مسبح خاص وحديقة واسعة بإطلالة ساحرة على البحر. تصميم عصري مع تشطيبات من الرخام الإيطالي الفاخر.",
    price: 8500,
    category: "عقارات",
    imageUrls: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80"],
    sellerId: "admin",
    sellerName: "سوق سند المتميز",
    location: "قرطاج، تونس",
    createdAt: new Date().toISOString(),
    plan: 'vip',
    status: 'active',
    views: 1250,
    likes: 345
  },
  {
    id: "2",
    title: "سيارة مرسيدس بنز الفئة S",
    description: "مرسيدس بنز S-Class 2024 بحالة الوكالة، العداد 5 آلاف كم فقط، داخلية جلد طبيعي فاخر مع شاشات خلفية.",
    price: 450000,
    category: "سيارات",
    imageUrls: ["https://images.unsplash.com/photo-1622194993926-14092b3a9ed6?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80"],
    sellerId: "admin",
    sellerName: "معرض الرفاهية",
    location: "سوسة",
    createdAt: new Date().toISOString(),
    plan: 'vip',
    status: 'active',
    views: 890,
    likes: 210
  },
  {
    id: "3",
    title: "ساعة رولكس صبมารيเนอร์",
    description: "ساعة رولكس صبمارينر أصلية بالكامل مع العلبة والأوراق كاملة. حالة ممتازة كالجديدة.",
    price: 45000,
    category: "مقتنيات",
    imageUrls: ["https://images.unsplash.com/photo-1523170335258-f5ed11844a49?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80"],
    sellerId: "admin",
    sellerName: "نخبة الساعات",
    location: "المرسى",
    createdAt: new Date().toISOString(),
    plan: 'bronze',
    status: 'active',
    views: 450,
    likes: 120
  },
  {
    id: "4",
    title: "طقم أثاث ملكي فاخر",
    description: "طقم كنب بتصميم كلاسيكي وزخرفة مذهبة مستورد من إيطاليا، مناسب للقصور والفلل الفاخرة.",
    price: 12000,
    category: "أثاث",
    imageUrls: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80"],
    sellerId: "admin",
    sellerName: "روائع الأثاث",
    location: "صفاقس",
    createdAt: new Date().toISOString(),
    plan: 'bronze',
    status: 'active',
    views: 320,
    likes: 85
  },
  {
    id: "5",
    title: "مجموعة عطور نادرة",
    description: "مجموعة حصرية من العطور الملكية النادرة ذات الإصدار المحدود.",
    price: 1500,
    category: "عطور",
    imageUrls: ["https://images.unsplash.com/photo-1594035987173-1644eee39b23?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80"],
    sellerId: "admin",
    sellerName: "عطور الشرق",
    location: "تونس العاصمة",
    createdAt: new Date().toISOString(),
    plan: 'free',
    status: 'active',
    views: 150,
    likes: 45
  },
  {
    id: "6",
    title: "يخت سياحي فخم",
    description: "يخت فرنسي الصنع موديل 2022 بطول 40 قدم، يحتوي على غرفتين وصالة للجلوس مع تجهيزات ملاحة كاملة.",
    price: 850000,
    category: "مركبات بحرية",
    imageUrls: ["https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80"],
    sellerId: "admin",
    sellerName: "مارين اكسكلوسيف",
    location: "الحمامات",
    createdAt: new Date().toISOString(),
    plan: 'vip',
    status: 'active',
    views: 2300,
    likes: 540
  }
];
